gestoralmacen/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import urls as accounts_urls
from tools import urls as tools_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(accounts_urls, namespace='accounts')),
    path('tools/', include(tools_urls, namespace='tools'))
]

tools/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import ListTools, DetailTool, CreateTool, UpdateTool, DeleteTool

app_name = 'tools'
urlpatterns = [
    path('', ListTools, name='list'),
    path('<int:id>/', DetailTool, name='detail'),
    path('create/', CreateTool.as_view(), name='create'),
    path('update/<int:id>/', UpdateTool.as_view(), name='update'),
    path('delete/', DeleteTool, name='delete')
]

tools/models.py
from django.db import models

class Tool(models.Model):
    name = models.CharField(max_length=140)
    serial_number = models.CharField(max_length=140)
    model = models.CharField(max_length=140)
    has_been_in_mainteance = models.BooleanField(default=False)
    mainteance_date = models.DateField(blank=True, null=True)
    is_in_maintain = models.BooleanField(default=False)
    specifications = models.TextField(blank=True, null=True)
    has_tracker = models.BooleanField(default=False)
    tracker_id = models.CharField(max_length=30, blank=True, null=True)

    def __str__(self):
        return self.name

tools/forms.py
from django import forms
from .models import Tool

class ToolForm(forms.ModelForm):
    name = forms.CharField(label='Nombre', required=True)
    serial_number = forms.CharField(label='Número de serie', required=True)
    model = forms.CharField(label='Modelo', required=True)
    has_been_in_mainteance = forms.BooleanField(label='¿Ha tenido mantenimiento?', required=False)
    mainteance_date = forms.DateField(
        label='Fecha de mantenimiento',
        widget=forms.SelectDateWidget(years=range(2010, 2022))
    )
    is_in_maintain = forms.BooleanField(label='¿Está en mantenimiento?', required=False)
    specifications = forms.CharField(label='Características', widget=forms.Textarea, required=False)
    has_tracker = forms.BooleanField(label='¿Cuenta con rastreador?', required=False)
    tracker_id = forms.CharField(label='Id del rastreador', required=False)
    class Meta:
        model = Tool
        fields = ('name', 'serial_number', 'model', 'has_been_in_mainteance',
            'mainteance_date', 'is_in_maintain', 'specifications',
            'has_tracker', 'tracker_id'
        )

tools/views.py
from django import views
from django.shortcuts import render, redirect
from .models import Tool
from .forms import ToolForm
from .utils import tools_form_validations

def ListTools(request):
    tools = Tool.objects.all()
    template_name = 'tools/list.html'
    context = {
        'tools': tools
    }
    return render(request, template_name, context)

def DetailTool(request, id):
    tool = Tool.objects.get(id=id)
    template_name = 'tools/detail.html'
    context = {
        'tool': tool
    }
    return render(request, template_name, context)

class CreateTool(views.View):
    template_name = 'tools/form.html'

    def get(self, request):
        form = ToolForm()
        context = {
            'form': form
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = ToolForm(data=request.POST)
        if form.is_valid():
            new_tool = form.save(commit=False)
            new_tool = tools_form_validations(form, new_tool)
            new_tool.save()
            return redirect('tools:list')
        else:
            context = {
                'form': form
            }
            return render(request, self.template_name, context)

class UpdateTool(views.View):
    template_name = 'tools/form.html'

    def get(self, request, id):
        tool = Tool.objects.get(id=id)
        form = ToolForm(instance=tool)
        context = {
            'form': form,
            'tool': tool,
            'is_update': True
        }
        return render(request, self.template_name, context)

    def post(self, request, id):
        tool = Tool.objects.get(id=id)
        tool_actual_is_in_maintain_value = tool.is_in_maintain
        form = ToolForm(instance=tool, data=request.POST)
        if form.is_valid():
            tool_updated = form.save(commit=False)
            tool_updated = tools_form_validations(form, tool_updated, tool_actual_is_in_maintain_value)
            tool_updated.save()
            return redirect('tools:detail', tool_updated.id)
        else:
            context = {
                'form': form
            }
            return render(request, self.template_name, context)

def DeleteTool(request):
    tool = Tool.objects.get(id=request.POST['id'])
    tool.delete()
    return redirect('tools:list')

tools/templates/tools/detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ tool.name }}</h1>
    <a href="{% url 'tools:update' tool.id %}"><button>Editar</button></a>
    <button id="delete-user">Eliminar Usuario</button>
    <form action="{% url 'tools:delete'%}" method="POST" style="visibility: hidden">
        {% csrf_token %}
        <input type="hidden" name="id" value={{ tool.id }}>
        <input type="submit" value="" id="send-form-delete">
    </form>
    <br>
    <hr>
    <br>
    <ul>
        <li>Número de serie: <b>{{ tool.serial_number }}</b></li>
        <li>Modelo: <b>{{ tool.model }}</b></li>
        <li>¿Ha tenido mantenimiento? <b>{% if tool.has_been_in_mainteance %}SI{% else %}NO{% endif %}</b></li>
        {% if tool.has_been_in_mainteance %}
            <li>Último mantenimiento: <b>{{ tool.mainteance_date|default_if_none:"Nunca se le ha dado mantenimiento" }}</b></li>
        {% endif %}
        <li>¿Está en mantenimiento? <b>{% if tool.is_in_maintain %}SI{% else %}NO{% endif %}</b></li>
        <li>Especificaciones: <b>{{ tool.specifications|default_if_none:"N/A" }}</b></li>
        <li>¿Tiene rastreador?: <b>{% if tool.has_tracker %}SI{% else %}NO{% endif %}</b></li>
        {% if tool.has_tracker %}
            <li>Indentificador del rastreador: <b>{{ tool.tracker_id|default_if_none:"No especificado aún" }}</b></li>
        {% endif %}
</ul>
{% endblock content %}

{% block scripts %}
    <script>
        const module = () => {
            const $deleteButton = document.querySelector('#delete-user');
            const $sendFormButton = document.querySelector('#send-form-delete');
            $deleteButton.addEventListener('click', () => {
                if (window.confirm('¿Estás seguro de querer eliminar esta herramienta?')) {
                    $sendFormButton.click();
                }
            })
        }
        module();
    </script>
{% endblock scripts %}

tools/templates/tools/form.html
{% extends 'base.html' %}

{% block content %}

    {% if is_update %}
        <h1>Actualiza datos de la herramientas {{ tool.name }}</h1>
    {% else %}
        <h1>Agrega una herramienta</h1>
    {% endif %}

    {% if is_update %}
        <form action="{% url 'tools:update' tool.id %}" method='POST'>
    {% else %}
        <form action="{% url 'tools:create' %}" method='POST'>
    {% endif %}
        {% csrf_token %}
        {{ form.as_p }}

        {% if is_update %}
            <input type="submit" value="Editar herramienta">
        {% else %}
            <input type="submit" value="Crear herramienta">
        {% endif %}
    </form>
{% endblock content %}

{% block scripts %}
    <script>
        const module = () => {

            const isUpdateAction = window.location.pathname.split('/').some(element => element === 'update');

            const $hasBeenMaintainedInput = document.querySelector('#id_has_been_in_mainteance');
            const $mainteanceDateElem = document.querySelector('#id_mainteance_date_day').parentNode;
            const $hasTrackerInput = document.querySelector('#id_has_tracker');
            const $trackerIdInput = document.querySelector('#id_tracker_id');
            const $trackerIdContainer = $trackerIdInput.parentNode;

            if (isUpdateAction) {
                if ($hasBeenMaintainedInput.checked) {
                    $mainteanceDateElem.style.display = 'block';
                } else {
                    $mainteanceDateElem.style.display = 'none';
                }

                if ($hasTrackerInput.checked) {
                    $trackerIdContainer.style.display = 'block';
                } else {
                    $trackerIdContainer.style.display = 'none';
                }
            } else {
                $trackerIdContainer.style.display = 'none';
                $mainteanceDateElem.style.display = 'none';
            }
            $hasTrackerInput.addEventListener('change', () => {
                if ($hasTrackerInput.checked) {
                    $trackerIdContainer.style.display = 'block';
                } else {
                    $trackerIdContainer.style.display = 'none';
                    $trackerIdInput.value = '';
                }
            });

            $hasBeenMaintainedInput.addEventListener('change', () => {
                if ($hasBeenMaintainedInput.checked) {
                    $mainteanceDateElem.style.display = 'block';
                } else {
                    $mainteanceDateElem.style.display = 'none';
                }
            })
        }
        module();
    </script>
{% endblock scripts %}

tools/templates/tools/list.html
{% extends 'base.html' %}

{% block content %}
<h1>Lista de herramientas</h1>
<br>
<hr>
{% if tools|length > 0 %}
    <ul>
        {% for tool in tools %}
            <a href="{% url 'tools:detail' tool.id %}">
                <li>{{ tool.name }} ({% if tool.is_in_maintain %}EN MANTENIMIENTO{% else %}DISPONIBLE{% endif %})</li>
            </a>
        {% endfor %}
    </ul>
{% else %}
    <p>No hay herramientas registradas</p>
{% endif %}
{% endblock content %}