accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import CreateUser, ListUsers, UserDetail, UpdateUser, DeleteUser

app_name = 'accounts'
urlpatterns = [
    path('', ListUsers, name='list'),
    path('<int:id>/', UserDetail, name='detail'),
    path('create/', CreateUser.as_view(), name='create'),
    path('update/<int:id>/', UpdateUser.as_view(), name='update'),
    path('delete/', DeleteUser, name='delete')
]

gestoralmacen/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import urls as accounts_urls
from tools import urls as tools_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(accounts_urls, namespace='accounts')),
    path('tools/', include(tools_urls, namespace='tools'))
]

tools/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import ListTools, DetailTool, CreateTool, UpdateTool, DeleteTool

app_name = 'tools'
urlpatterns = [
    path('', ListTools, name='list'),
    path('<int:id>/', DetailTool, name='detail'),
    path('create/', CreateTool.as_view(), name='create'),
    path('update/<int:id>/', UpdateTool.as_view(), name='update'),
    path('delete/', DeleteTool, name='delete')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class WorkerUser(AbstractUser):
    phone_number = models.CharField(max_length=13)
    job_title = models.CharField(max_length=140)
    rest_time = models.CharField(max_length=140)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

accounts/forms.py
from django import forms
from .models import WorkerUser

user_type_choices_dropdown = (
    ('', 'Selecciona:'), ('true', 'Usuario Supervisor'), ('false', 'Usuario Técnico')
)

class WorkerUserForm(forms.ModelForm):
    first_name = forms.CharField(label='Nombre(s)', required=True)
    last_name = forms.CharField(label='Apellidos', required=True)
    username = forms.CharField(label='Nombre de Usuario (Sólo lectura)', widget=forms.TextInput(attrs={'readonly': True}))
    phone_number = forms.CharField(label='Número telefónico')
    email = forms.CharField(widget=forms.EmailInput(), label='Correo Electrónico')
    job_title = forms.CharField(label='Puesto')
    rest_time = forms.CharField(label = 'Descanso')
    is_staff = forms.BooleanField(required=False)
    is_supervisor = forms.ChoiceField(choices=user_type_choices_dropdown, label='Selecciona tipo de usuario')
    password = forms.CharField(widget=forms.PasswordInput(), label='Contraseña')
    class Meta:
        model = WorkerUser
        fields = ('first_name', 'last_name', 'username', 'email', 'phone_number', 'job_title', 'rest_time', 'is_supervisor', 'is_staff', 'password')

class WorkerUserFormEdit(forms.ModelForm):
    first_name = forms.CharField(label='Nombre(s)', required=True)
    last_name = forms.CharField(label='Apellidos', required=True)
    # username = forms.CharField(label='Nombre de Usuario (Sólo lectura)', widget=forms.TextInput(attrs={'readonly': True}))
    phone_number = forms.CharField(label='Número telefónico')
    email = forms.CharField(widget=forms.EmailInput(), label='Correo Electrónico')
    job_title = forms.CharField(label='Puesto')
    rest_time = forms.CharField(label = 'Descanso')
    is_staff = forms.BooleanField(required=False)
    is_supervisor = forms.ChoiceField(choices=user_type_choices_dropdown, label='Selecciona tipo de usuario')
    class Meta:
        model = WorkerUser
        fields = (
            'first_name',
            'last_name',
        #    'username',
            'email',
            'phone_number',
            'job_title',
            'rest_time',
            'is_supervisor',
            'is_staff'
        )

accounts/views.py
from django import views
from django.shortcuts import render, redirect
from .models import WorkerUser
from .forms import WorkerUserForm, WorkerUserFormEdit

def ListUsers(request):
    supervisors = WorkerUser.objects.filter(is_staff=True, is_active=True, is_superuser=False)
    technicians = WorkerUser.objects.filter(is_staff=False, is_active=True, is_superuser=False)
    template_name = 'accounts/list.html'
    context = {
        'supervisors': supervisors,
        'technicians': technicians
    }
    return render(request, template_name, context)

def UserDetail(request, id):
    user = WorkerUser.objects.get(id=id)
    template_name = 'accounts/detail.html'
    context = {
        'user': user
    }
    return render(request, template_name, context)

class CreateUser(views.View):
    template_name = 'accounts/form.html'

    def get(self, request):
        form = WorkerUserForm()
        context = {
            'form': form
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = WorkerUserForm(data=request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            return redirect('accounts:list')
        else:
            return render(request, self.template_name, {})

class UpdateUser(views.View):
    template_name = 'accounts/form.html'

    def get(self, request, id):
        user = WorkerUser.objects.get(id=id)
        form = WorkerUserFormEdit(instance=user)
        context = {
            'is_update': True,
            'user_id': user.id,
            'form': form
        }
        return render(request, self.template_name, context)

    def post(self, request, id):
        user = WorkerUser.objects.get(id=id)
        form = WorkerUserFormEdit(data=request.POST, instance=user)
        if form.is_valid():
            user = form.save()
            return redirect('accounts:detail', user.id)
        else:
            context = {
                'form': form
            }
            return render(request, self.template_name, context)

def DeleteUser(request):
    user = WorkerUser.objects.get(id=request.POST['id'])
    user.delete()
    return redirect('accounts:list')

accounts/templates/accounts/detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ user.first_name }} {{ user.last_name }}</h1>
    <hr>
    <p><b>Nombre de Usuario:</b> {{ user.username }}</p>
    <p><b>Correo Electrónico:</b> {{ user.email }}</p>
    <p><b>Número telefónico:</b> {{ user.phone_number }}</p>
    <p><b>Puesto:</b> {{ user.job_title }}</p>
    <p><b>Descanso:</b> {{ user.rest_time }}</p>
    <p><b>Tipo de Usuario:</b> {% if user.is_staff %}Supervisor{% else %}Técnico{% endif %}</p>
    <hr>
    <a href="{% url 'accounts:update' user.id %}"><button>Editar Usuario</button></a>
    <button id="delete-user">Eliminar Usuario</button>
    <form action="{% url 'accounts:delete'%}" method="POST" style="visibility: hidden">
        {% csrf_token %}
        <input type="hidden" name="id" value={{ user.id }}>
        <input type="submit" value="" id="send-form-delete">
    </form>
{% endblock content %}

{% block scripts %}
    <script>
        const module = () => {
            const $deleteButton = document.querySelector('#delete-user');
            const $sendFormButton = document.querySelector('#send-form-delete');
            $deleteButton.addEventListener('click', () => {
                if (window.confirm('¿Estás seguro de querer eliminar este usuario?')) {
                    $sendFormButton.click();
                }
            })
        }
        module();
    </script>
{% endblock scripts %}

accounts/templates/accounts/form.html
{% extends 'base.html' %}

{% block content %}
    {% if is_update %}
    <form action="{% url 'accounts:update' user_id %}" method="POST">
    {% else %}
    <form action="{% url 'accounts:create' %}" method="POST">
    {% endif %}
    {% csrf_token %}
        {{ form.as_p }}
        {% if is_update %}
        <input type="submit" value="Editar usuario">
        {% else %}
        <input type="submit" value="Crear usuario">
        {% endif %}
    </form>
{% endblock content %}

{% block scripts %}
    <script>
        const module = () => {
            const defaultPassword = 'defaultPassword1234';

            const isUpdateAction = window.location.pathname.split('/').some(element => element === 'update');

            const $dropdown = document.querySelector('#id_is_supervisor');
            const $isStaffInput = document.querySelector('#id_is_staff');
            const $firstNameInput = document.querySelector('#id_first_name');
            const $lastNameInput = document.querySelector('#id_last_name');
            const $isStaffElem = document.querySelector('#id_is_staff').parentNode;
            $isStaffElem.style.display = 'none';
            let $passwordInput;
            let $passwordElem;
            let $usernameInput;

            if (isUpdateAction) {
                const $optionSupervisor = document.querySelector('option[value="true"]');
                const $optionTechnician = document.querySelector('option[value="false"]');
                if ($isStaffInput.checked) {
                    $optionSupervisor.selected = true;
                } else {
                    $optionTechnician.selected = true;
                }
            }

            if (!isUpdateAction) {
                $passwordInput = document.querySelector('#id_password');
                $passwordElem = document.querySelector('#id_password').parentNode;
                $usernameInput = document.querySelector('#id_username');
                $passwordElem.style.display = 'none';
            };

            $dropdown.addEventListener('change', (event) => {
                if (event.target.value === 'true') {
                    $isStaffInput.checked = true;

                    if (!isUpdateAction) {
                        $passwordElem.style.display = 'block';
                        $passwordInput.value = '';
                    }
                } else {
                    $isStaffInput.checked = false;

                    if (!isUpdateAction) {
                        $passwordElem.style.display = 'none';
                        $passwordInput.value = defaultPassword;
                    };
                };
            });

            if (!isUpdateAction) {
                const sanitizeNames = (name) => name.toLowerCase().replace(' ', '_');
                const setUsernameValue = (event) => {
                    $usernameInput.value = `${sanitizeNames($firstNameInput.value)}_${sanitizeNames($lastNameInput.value)}`;
                };
                $firstNameInput.addEventListener('change', event => setUsernameValue(event));
                $lastNameInput.addEventListener('change', event => setUsernameValue(event));
            };
        };
        module();
    </script>
{% endblock scripts %}

accounts/templates/accounts/list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Lista de usuarios</h1>
    <hr>
    <h3>Supervisores</h3>
    {% if supervisors|length > 0 %}
        <ul>
        {% for supervisor in supervisors %}
            <a href="{% url 'accounts:detail' supervisor.id %}">
                <li>{{ supervisor.first_name }} {{ supervisor.last_name }}</li>
            </a>
        {% endfor %}
        </ul>
    {% else %}
        <p>No hay usuarios supervisores registrados</p>
    {% endif %}
    <br>
    <hr>
    <br>
    <h3>Técnicos</h3>
    {% if technicians|length > 0 %}
        <ul>
        {% for technician in technicians %}
            <a href="{% url 'accounts:detail' technician.id %}">
                <li>{{ technician.first_name }} {{ technician.last_name }}</li>
            </a>
        {% endfor %}
        <ul>
    {% else %}
        <p>No hay usuarios técnicos registrados</p>
    {% endif %}

{% endblock content %}