gestoralmacen/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import urls as accounts_urls
from tools import urls as tools_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(accounts_urls, namespace='accounts')),
    path('tools/', include(tools_urls, namespace='tools'))
]

tools/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import ListTools, DetailTool, CreateTool, UpdateTool, DeleteTool

app_name = 'tools'
urlpatterns = [
    path('', ListTools, name='list'),
    path('<int:id>/', DetailTool, name='detail'),
    path('create/', CreateTool.as_view(), name='create'),
    path('update/<int:id>/', UpdateTool.as_view(), name='update'),
    path('delete/', DeleteTool, name='delete')
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestor Almacen</title>
</head>
<body>
    <ul>
        <a href="{% url 'accounts:list' %}"><li>Lista de usuarios</li></a>
        <a href="{% url 'accounts:create' %}"><li>Crear un usuario</li></a>
        <a href="{% url 'tools:list' %}"><li>Lista de herramientas</li></a>
        <a href="{% url 'tools:create' %}"><li>Crear una herramienta</li></a>
    </ul>
    {% block content %}
    {% endblock content %}

    {% block scripts %}
    {% endblock scripts %}
</body>
</html>